/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abdulaziz;

import javax.swing.JOptionPane;

/**
 *
 * @author ASER
 */
public class dashboard extends javax.swing.JFrame {

    connect c = new connect();

    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewProducts = new javax.swing.JButton();
        AddProducts = new javax.swing.JButton();
        BackProducts = new javax.swing.JButton();
        GetProducts = new javax.swing.JButton();
        AddControlling = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ViewProducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewProducts.setText("ViewProducts");
        ViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductsActionPerformed(evt);
            }
        });

        AddProducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddProducts.setText("AddProducts");
        AddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductsActionPerformed(evt);
            }
        });

        BackProducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackProducts.setText("BackProducts");
        BackProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackProductsActionPerformed(evt);
            }
        });

        GetProducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GetProducts.setText("GetProducts");
        GetProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetProductsActionPerformed(evt);
            }
        });

        AddControlling.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddControlling.setText("AddControlling");
        AddControlling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddControllingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Welcome to the store  of Computer Science");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BackProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(ViewProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(AddControlling, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(GetProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(AddProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ViewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddControlling, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductsActionPerformed
        AddProducts AP = new AddProducts();
        AP.setLocationRelativeTo(AP);
        AP.setTitle("AddProducts");
        AP.setVisible(true);
        AP.setSize(922, 722);
        AP.setLocation(220, 10);
        this.dispose();
    }//GEN-LAST:event_AddProductsActionPerformed

    private void ViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductsActionPerformed
        ViewProducts VP = new ViewProducts();
        VP.setLocationRelativeTo(VP);
        VP.setTitle("AddProducts");
        VP.setVisible(true);
        VP.setSize(922, 722);
        VP.setLocation(220, 10);
        this.dispose();
    }//GEN-LAST:event_ViewProductsActionPerformed

    private void AddControllingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddControllingActionPerformed

        String s1 = JOptionPane.showInputDialog("enter username");
        String s2 = JOptionPane.showInputDialog("enter password");
        try {
            c.rs = c.stmt.executeQuery("select * from users where username='" + s1 + "' and password='" + s2 + "' and type= 'Admin' ");
            if (c.rs.next()) {
                AddControlling AC = new AddControlling();
                AC.setLocationRelativeTo(AC);
                AC.setTitle("AddProducts");
                AC.setVisible(true);
                AC.setSize(922, 722);
                AC.setLocation(220, 10);
                this.dispose();
            } else {
                JOptionPane.showConfirmDialog(null, "UesrName Or Password Error");
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Error in connection");
        }

    }//GEN-LAST:event_AddControllingActionPerformed

    private void BackProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackProductsActionPerformed
        BackProducts BP = new BackProducts();
        BP.setLocationRelativeTo(BP);
        BP.setTitle("AddProducts");
        BP.setVisible(true);
        BP.setSize(922, 722);
        BP.setLocation(220, 10);
        this.dispose();
    }//GEN-LAST:event_BackProductsActionPerformed

    private void GetProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetProductsActionPerformed
        GetProducts GP = new GetProducts();
        GP.setLocationRelativeTo(GP);
        GP.setTitle("AddProducts");
        GP.setVisible(true);
        GP.setSize(922, 722);
        GP.setLocation(220, 10);
        this.dispose();
    }//GEN-LAST:event_GetProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddControlling;
    private javax.swing.JButton AddProducts;
    private javax.swing.JButton BackProducts;
    private javax.swing.JButton GetProducts;
    private javax.swing.JButton ViewProducts;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
